import express from "express";
import { activeCollectionController, createCollectionController, deleteByIdController, getAllCollectionController, getCollectionByIdController, updateCollectionController } from "../controllers/collectionController.js";
const collectionRouter = express.Router();
collectionRouter.get("/", getAllCollectionController);
collectionRouter.get("/:id", getCollectionByIdController);
collectionRouter.delete("/:id", deleteByIdController);
collectionRouter.put("/:id/active", activeCollectionController);
collectionRouter.post("/", createCollectionController);
collectionRouter.put("/:id", updateCollectionController);
export default collectionRouter;